name: Hugo Build CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Hugo
      run: sudo apt update;sudo apt install hugo
    - name: Build
      run: |
        hugo -D